spring.application.name=spotify-backend
spotify.client-id=5774fb96e96741c0b2d984b22ac28b99
spotify.playlist-id=7xBLtlRNkinBdkNYy0BafL
spotify.client-secret=18e942f6cde145b7bc03b1439bb551a7
spotify.token-url=http://accounts.spotify.com/api/token
spotify.persisted-refresh-token=http://accounts.spotify.com/api/token
spotify.redirect-uri=http://127.0.0.1:8080/callback
spotify.scopes=playlist-modify-private,playlist-modify-public,playlist-read-private
spotify.base-url=https://api.spotify.com/v1
spotify.current-refresh-token=AQDeQMBFAOWJyWCIwQk0lVMrqPEH7Vto32Oe21aECOhuzr5wRaxSt31YXEjpGgghPI2HQMPEnUTnUQ15Ui4RsNVZN7O_qPx2tWFkMX1ZDFPMFdt7u7dC6cjw3qoYFGC_kXQ